name: tests

on:
  push:
  pull_request:

jobs:
  unittest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run tests
        run: python -m unittest discover
      - name: Compile
        run: python -m py_compile .\xmind_to_feishu.py .\test_xmind_to_feishu.py
